version: '2'

services:
  app:
    tty: true
    container_name: test.django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/docker-platoe/test_static_volume:/platoe/static_volume
      - /home/ubuntu/docker-platoe/test_media_volume:/platoe/media_volume
    environment:
      - DEBUG=0
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_SETTINGS_MODULE=test-settings
      - DB_PASSWORD=ajij%@6gav82!hsA8V8j7

  web:
    container_name: test.nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - /home/ubuntu/docker-platoe/test_static_volume:/static_volume
      - /home/ubuntu/docker-platoe/test_media_volume:/media_volume

