version: "2"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
#    volumes:
#      - ./:/platoe
#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=test-settings
