version: '2'

services:
  app:
    container_name: platoe
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=test-settings
      - DB_PASSWORD=ajij%@6gav82!hsA8V8j7

  web:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
