---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-static-pv
spec:
  storageClassName: nfs-static-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: dbtest.platoe.io
    path: /mnt/nfs_share/static

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  storageClassName: nfs-media-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: dbtest.platoe.io
    path: /mnt/nfs_share/media

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static-pvc
spec:
  storageClassName: nfs-static-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
spec:
  storageClassName: nfs-media-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-settings
data:
  DEBUG: "0"
  DJANGO_LOG_LEVEL: "DEBUG"
  DJANGO_SETTINGS_MODULE: "test-settings"
  DB_PASSWORD: "ajij%@6gav82!hsA8V8j7"




