# Generated by Django 3.1.1 on 2020-10-02 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_requested', models.BooleanField()),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('subject', models.CharField(choices=[('AUTO', 'Automotive'), ('EL', 'Electronics'), ('ART', 'Arts'), ('SPT', 'Sports'), ('FSH', 'Fashion'), ('HME', 'Home'), ('RE', 'Real Estate'), ('PET', 'Pets'), ('IND', 'Industry'), ('KID', 'Kids')], max_length=50)),
                ('goal', models.CharField(max_length=292)),
                ('context', models.CharField(blank=True, max_length=2048)),
                ('offer_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=1111111),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shared_Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_time', models.DateTimeField(auto_now_add=True)),
                ('shared_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('site_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transferred_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idea_shared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_shared_ideas', to='ideas.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_timestamp', models.DateTimeField(auto_now_add=True)),
                ('rated_shared_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.shared_idea')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_ideas', to='ideas.request'),
        ),
        migrations.AddField(
            model_name='idea',
            name='idealist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
