# Generated by Django 3.1.1 on 2020-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_auto_20201013_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
    ]
