# Generated by Django 3.1.1 on 2020-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_user_failed_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
