# Generated by Django 3.1.1 on 2020-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_auto_20201019_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(),
        ),
    ]
