# Generated by Django 3.1.1 on 2020-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_auto_20201019_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
