# Generated by Django 3.1.2 on 2020-11-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_auto_20201020_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(choices=[('COM', 'Company'), ('PRO', 'Product'), ('SVC', 'Service'), ('ART', 'Art'), ('OBJ', 'Object'), ('MOV', 'Movie'), ('TXT', 'Text'), ('BOK', 'Book'), ('OTH', 'Other')], max_length=50),
        ),
    ]
