# Generated by Django 3.1.1 on 2020-11-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_auto_20201110_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='attachments',
            field=models.FileField(blank=True, upload_to='ideas_files'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
