# Generated by Django 3.1.1 on 2020-11-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_auto_20201118_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_requested',
        ),
    ]
