# Generated by Django 3.1.1 on 2020-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0020_auto_20201118_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.CharField(max_length=2048),
        ),
    ]
