# Generated by Django 3.1.1 on 2021-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0022_auto_20210112_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
