# Generated by Django 3.1.1 on 2021-01-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0025_auto_20210112_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stripe_Account',
            new_name='Bank_Account',
        ),
    ]
