# Generated by Django 3.1.1 on 2021-01-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0026_auto_20210112_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank_Account',
        ),
    ]
