# Generated by Django 3.1.1 on 2021-01-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0028_auto_20210113_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_account',
            name='stripe_id',
            field=models.CharField(default='none', max_length=21, unique=True),
            preserve_default=False,
        ),
    ]
