# Generated by Django 3.1.1 on 2021-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0029_stripe_account_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_account',
            name='stripe_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
