# Generated by Django 3.1.1 on 2021-01-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0031_idea_idea_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea_timestamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='idea',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
