# Generated by Django 3.1.1 on 2021-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0032_auto_20210115_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(default='created', max_length=12),
        ),
    ]
