# Generated by Django 3.1.1 on 2021-01-17 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0034_auto_20210115_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=30, unique=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_payment_intents', to='ideas.idea')),
                ('payment_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
