# Generated by Django 3.1.1 on 2021-01-18 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0035_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_intent',
            name='payment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_intents', to=settings.AUTH_USER_MODEL),
        ),
    ]
