# Generated by Django 3.1.1 on 2021-01-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0037_auto_20210118_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='definition',
            field=models.CharField(choices=[('COM_NAME', 'Idea for a Company Name'), ('COM_SLOGAN', 'Idea for a Company Slogan'), ('COM_BM', 'Idea for a Business Model'), ('COM_ASSET', 'Idea for a Company Asset'), ('COM_EV', 'Idea for a Company Event'), ('PRO_TOY', 'Idea for a Toy'), ('PRO_HOUSE', 'Idea for a House Item'), ('PRO_GADGET', 'Idea for a Gadget'), ('PRO_TECH', 'Idea for a Technology'), ('PRO_FEATURE', 'Idea for a Feature'), ('SVC_NEW', 'Idea for a New Service'), ('ART_MUS', 'Idea for a Music'), ('ART_DRAW', 'Idea for a Drawing'), ('ART_DANCE', 'Idea for a Dance'), ('OBJ_PRESENT', 'Idea for a Present'), ('OBJ_DECORATION', 'Idea for a Decoration'), ('OBJ_INVENTION', 'Idea for an Invention'), ('MOV_TITLE', 'Idea for a Title'), ('MOV_SCRIPT', 'Idea for a Script'), ('MOV_CHAR', 'Idea for a Character'), ('MOV_SCENE', 'Idea for a Scene'), ('TXT_LYRIC', 'Idea for a Lyric'), ('TXT_SCRIPT', 'Idea for a Script'), ('TXT_CHARACTER', 'Idea for a Character'), ('TXT_LETTER', 'Idea for a Letter'), ('OTH', 'Idea for something else')], max_length=50),
        ),
    ]
