# Generated by Django 3.1.1 on 2021-01-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0038_auto_20210118_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_account',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='stripe_account',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
