pipeline{
    agent{ node("dev.platoe.io") }
    stages{
        stage("PingSelf") {
            steps {
                sh "ping dev.platoe.io -c 1"
            }
        }
        stage("Git"){
            steps{
                sh '''
                cd ${HOME}
                echo "Current Directory: ${PWD}"
                mkdir -p ${HOME}/dev.platoe
                '''
                git credentialsId: 'jenkins-webhook',
                url: 'https://github.com/videap/platoe.git',
                branch: 'dev'
            }
        }
        stage("RunScript"){
            steps{
                sh '${HOME}/dev.platoe/platoe/jenkins/scripts/dev_setup.sh'
            }
        }
    }
}
