pipeline{
    agent{ node("dev.platoe.io") }
    stages{
        stage("PingSelf") {
            steps {
                sh "ping dev.platoe.io -c 1"
            }
        }
        stage("CurrentDirectory"){
            steps{
                sh '''
                echo "This is the current directory:"
                pwd
            }
        }
    }
}
