pipeline{
    agent{ node("dev.platoe.io") }
    stages{
        stage("PingSelf") {
            steps {
                sh "ping 129.159.51.19 -c 1"
            }
        }
        stage("LastLogin"){
            steps{
                sh '''
                echo "This is the current directory:"
                $PWD
                date >> last_login
                '''
            }
        }
    }
}
